import { WebhookRegistryEntry } from './webhook.registry';
import { AppEnvName } from '../config/config.schema';

const ALL_ENVS: AppEnvName[] = ['staging-us', 'prod-us', 'prod-eu', 'prod-in'];

export const GROUP_REGISTRY: WebhookRegistryEntry[] = [
  {
    id: 'group_created',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Create group',
    expectedEvent: 'group_created',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.group.name', 'data.group.type', 'data.group.owner'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-created.spec.ts',
    testTitleMatch: 'group_created webhook fires with correct guid, name, type and owner',
  },
  {
    id: 'group_updated',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Update group name',
    expectedEvent: 'group_updated',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.group.name'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-updated.spec.ts',
    testTitleMatch: 'group_updated webhook fires with the new name applied',
  },
  {
    id: 'group_deleted',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Delete group',
    expectedEvent: 'group_deleted',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-deleted.spec.ts',
    testTitleMatch: 'group_deleted webhook fires for the deleted guid',
  },
  {
    id: 'group_member_added',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Add member to group (REST, on behalf of owner)',
    expectedEvent: 'group_member_added',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.members', 'data.by'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-added.spec.ts',
    testTitleMatch: 'group_member_added webhook fires with correct member and actor',
  },
  {
    id: 'group_member_kicked',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Remove group member',
    expectedEvent: 'group_member_kicked',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.members', 'data.by'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-kicked.spec.ts',
    testTitleMatch: 'group_member_kicked webhook fires with correct member and actor',
  },
  {
    id: 'group_member_banned',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Ban group member',
    expectedEvent: 'group_member_banned',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.members', 'data.by'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-banned.spec.ts',
    testTitleMatch: 'group_member_banned webhook fires with correct member and actor',
    reason:
      'AUTOMATED, but expect this test to report as an *expected* failure: confirmed live CometChat bug — ' +
      'when Ban Member is called with onBehalfOf, data.members incorrectly contains the actor\'s UID instead ' +
      'of the banned target\'s. Reproduced outside this suite too, so not a test artifact.',
  },
  {
    id: 'group_member_unbanned',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Unban group member',
    expectedEvent: 'group_member_unbanned',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.members', 'data.by'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-unbanned.spec.ts',
    testTitleMatch: 'group_member_unbanned webhook fires with correct member and actor',
    reason: 'Same confirmed CometChat bug as group_member_banned above.',
  },
  {
    id: 'group_member_scope_changed',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: "Change a member's scope",
    expectedEvent: 'group_member_scope_changed',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.members'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-scope-changed.spec.ts',
    testTitleMatch: 'group_member_scope_changed webhook fires with old and new scope',
  },
  {
    id: 'group_owner_transferred',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'Transfer group ownership',
    expectedEvent: 'group_owner_transferred',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.group.guid', 'data.group.owner', 'data.group.oldOwner'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-owner-transferred.spec.ts',
    testTitleMatch: 'group_owner_transferred webhook fires with correct old and new owner',
  },
  {
    id: 'group_member_joined',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'A real SDK client self-joins a public group (no REST equivalent — verified live)',
    expectedEvent: 'group_member_joined',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.group.guid', 'data.group.owner', 'data.members'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-joined.spec.ts',
    testTitleMatch: 'group_member_joined webhook fires when a user joins a public group themselves',
  },
  {
    id: 'group_member_left',
    category: 'GROUP',
    environments: ALL_ENVS,
    trigger: 'A real SDK client self-leaves a group (no REST equivalent — verified live)',
    expectedEvent: 'group_member_left',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.group.guid', 'data.members'],
    status: 'AUTOMATED',
    specFile: 'src/tests/group/group-member-left.spec.ts',
    testTitleMatch: 'group_member_left webhook fires when a user leaves a group themselves',
  },
];
