import { WebhookRegistryEntry } from './webhook.registry';
import { AppEnvName } from '../config/config.schema';

const ALL_ENVS: AppEnvName[] = ['staging-us', 'prod-us', 'prod-eu', 'prod-in'];

export const MESSAGE_REGISTRY: WebhookRegistryEntry[] = [
  {
    id: 'message_sent',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Send a text message',
    expectedEvent: 'message_sent',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.sender', 'data.message.receiver', 'data.message.data.text'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-sent.spec.ts',
    testTitleMatch: 'message_sent webhook fires when a text message is sent',
  },
  {
    id: 'message_edited',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Edit an existing message',
    expectedEvent: 'message_edited',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.data.text'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-edited.spec.ts',
    testTitleMatch: 'message_edited webhook fires when a message is edited, with the new text',
  },
  {
    id: 'message_deleted',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Delete a message',
    expectedEvent: 'message_deleted',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-deleted.spec.ts',
    testTitleMatch: 'message_deleted webhook fires when a message is deleted',
  },
  {
    id: 'message_reaction_added',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Add a reaction to a message',
    expectedEvent: 'message_reaction_added',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.reaction.messageId', 'data.reaction.reaction', 'data.reaction.reactedBy'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-reaction-added.spec.ts',
    testTitleMatch: 'message_reaction_added webhook fires with the correct emoji, message and reactor',
  },
  {
    id: 'message_reaction_removed',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Remove a reaction from a message',
    expectedEvent: 'message_reaction_removed',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.reaction.messageId', 'data.reaction.reaction', 'data.reaction.reactedBy'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-reaction-removed.spec.ts',
    testTitleMatch: 'message_reaction_removed webhook fires with the correct emoji, message and reactor',
  },
  {
    id: 'user_mentioned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Send a message containing <@uid:...>',
    expectedEvent: 'user_mentioned',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.data.mentions'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/user-mentioned.spec.ts',
    testTitleMatch: 'user_mentioned webhook fires when a message mentions a user',
  },
  {
    id: 'message_delivery_receipt',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'A real SDK client calls markAsDelivered (no REST equivalent — verified live)',
    expectedEvent: 'message_delivery_receipt',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.body.user.uid', 'data.sender', 'data.messageSender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-delivery-receipt.spec.ts',
    testTitleMatch: 'message_delivery_receipt webhook fires when a recipient client acknowledges delivery',
  },
  {
    id: 'message_read_receipt',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'A real SDK client calls markAsRead (no REST equivalent — verified live)',
    expectedEvent: 'message_read_receipt',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.body.user.uid', 'data.sender', 'data.messageSender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-read-receipt.spec.ts',
    testTitleMatch: 'message_read_receipt webhook fires when a recipient client marks a message read',
  },
  {
    id: 'message_delivered_to_all',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Group message, sole other member marks it delivered (verified live: group-only, never fires in 1:1)',
    expectedEvent: 'message_delivered_to_all',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.sender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-delivered-to-all.spec.ts',
    testTitleMatch: 'message_delivered_to_all webhook fires once every group member has received the message',
  },
  {
    id: 'message_read_by_all',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Group message, sole other member marks it read (verified live: group-only, never fires in 1:1)',
    expectedEvent: 'message_read_by_all',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.sender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-read-by-all.spec.ts',
    testTitleMatch: 'message_read_by_all webhook fires once every group member has read the message',
  },
  {
    id: 'message_pinned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Pin a message (requires the Pin Message extension)',
    expectedEvent: 'message_pinned',
    automationMethod: 'REST',
    expectedPayloadKeys: [],
    status: 'NOT_IMPLEMENTED',
    specFile: 'src/tests/message/message-gaps.spec.ts',
    testTitleMatch: 'message_pinned (documented gap)',
    reason:
      'Live-probed 2026-09-04 against prod-eu: "Pin Message" exists as a catalog extension ' +
      '(GET /extensions/pin-message returns real metadata), but GET /extensions returns [] — the extension ' +
      "is NOT currently enabled on this app. Two guessed action-endpoint paths (POST /extensions/pin-message, " +
      'POST /v1/pin) both 404 with ERR_API_NOT_FOUND, so the real pin/unpin endpoint is unconfirmed — CometChat\'s ' +
      "public docs only show it called via the JS SDK's CometChat.callExtension('pin-message', 'POST', 'v1/pin', ...), " +
      "not a documented flat REST path. Also not listed in CometChat's own webhook trigger documentation at all. " +
      'Needs: (1) Pin Message enabled in Dashboard -> Chat & Messaging -> Features on a target app, (2) the real ' +
      'REST/SDK call path confirmed (not guessed), (3) confirmation this actually fires a message_pinned webhook.',
  },
  {
    id: 'message_unpinned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Unpin a message (requires the Pin Message extension)',
    expectedEvent: 'message_unpinned',
    automationMethod: 'REST',
    expectedPayloadKeys: [],
    status: 'NOT_IMPLEMENTED',
    specFile: 'src/tests/message/message-gaps.spec.ts',
    testTitleMatch: 'message_unpinned (documented gap)',
    reason: 'Same root cause as message_pinned above.',
  },
  {
    id: 'conversation_pinned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Pin a conversation',
    expectedEvent: 'conversation_pinned',
    automationMethod: 'REST',
    expectedPayloadKeys: [],
    status: 'NOT_IMPLEMENTED',
    specFile: 'src/tests/message/message-gaps.spec.ts',
    testTitleMatch: 'conversation_pinned (documented gap)',
    reason:
      'Searched CometChat\'s public docs and extension catalog 2026-09-04 — zero trace of this trigger or any ' +
      'REST/SDK endpoint for pinning a conversation (distinct from pinning a message). Not in the webhook events ' +
      'documentation, not a discoverable extension. Needs the exact trigger mechanism confirmed — likely only ' +
      "visible in the Dashboard's own webhook trigger checkboxes, which may be ahead of the public docs.",
  },
  {
    id: 'conversation_unpinned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Unpin a conversation',
    expectedEvent: 'conversation_unpinned',
    automationMethod: 'REST',
    expectedPayloadKeys: [],
    status: 'NOT_IMPLEMENTED',
    specFile: 'src/tests/message/message-gaps.spec.ts',
    testTitleMatch: 'conversation_unpinned (documented gap)',
    reason: 'Same root cause as conversation_pinned above.',
  },
];
