import { WebhookRegistryEntry } from './webhook.registry';
import { AppEnvName } from '../config/config.schema';

const ALL_ENVS: AppEnvName[] = ['staging-us', 'prod-us', 'prod-eu', 'prod-in'];

export const MESSAGE_REGISTRY: WebhookRegistryEntry[] = [
  {
    id: 'message_sent',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Send a text message',
    expectedEvent: 'message_sent',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.sender', 'data.message.receiver', 'data.message.data.text'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-sent.spec.ts',
    testTitleMatch: 'message_sent webhook fires when a text message is sent',
  },
  {
    id: 'message_edited',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Edit an existing message',
    expectedEvent: 'message_edited',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.data.text'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-edited.spec.ts',
    testTitleMatch: 'message_edited webhook fires when a message is edited, with the new text',
  },
  {
    id: 'message_deleted',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Delete a message',
    expectedEvent: 'message_deleted',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-deleted.spec.ts',
    testTitleMatch: 'message_deleted webhook fires when a message is deleted',
  },
  {
    id: 'message_reaction_added',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Add a reaction to a message',
    expectedEvent: 'message_reaction_added',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.reaction.messageId', 'data.reaction.reaction', 'data.reaction.reactedBy'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-reaction-added.spec.ts',
    testTitleMatch: 'message_reaction_added webhook fires with the correct emoji, message and reactor',
  },
  {
    id: 'message_reaction_removed',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Remove a reaction from a message',
    expectedEvent: 'message_reaction_removed',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.reaction.messageId', 'data.reaction.reaction', 'data.reaction.reactedBy'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-reaction-removed.spec.ts',
    testTitleMatch: 'message_reaction_removed webhook fires with the correct emoji, message and reactor',
  },
  {
    id: 'user_mentioned',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Send a message containing <@uid:...>',
    expectedEvent: 'user_mentioned',
    automationMethod: 'REST',
    expectedPayloadKeys: ['data.message.id', 'data.message.data.mentions'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/user-mentioned.spec.ts',
    testTitleMatch: 'user_mentioned webhook fires when a message mentions a user',
  },
  {
    id: 'message_delivery_receipt',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'A real SDK client calls markAsDelivered (no REST equivalent — verified live)',
    expectedEvent: 'message_delivery_receipt',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.body.user.uid', 'data.sender', 'data.messageSender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-delivery-receipt.spec.ts',
    testTitleMatch: 'message_delivery_receipt webhook fires when a recipient client acknowledges delivery',
  },
  {
    id: 'message_read_receipt',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'A real SDK client calls markAsRead (no REST equivalent — verified live)',
    expectedEvent: 'message_read_receipt',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.body.user.uid', 'data.sender', 'data.messageSender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-read-receipt.spec.ts',
    testTitleMatch: 'message_read_receipt webhook fires when a recipient client marks a message read',
  },
  {
    id: 'message_delivered_to_all',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Group message, sole other member marks it delivered (verified live: group-only, never fires in 1:1)',
    expectedEvent: 'message_delivered_to_all',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.sender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-delivered-to-all.spec.ts',
    testTitleMatch: 'message_delivered_to_all webhook fires once every group member has received the message',
  },
  {
    id: 'message_read_by_all',
    category: 'MESSAGE',
    environments: ALL_ENVS,
    trigger: 'Group message, sole other member marks it read (verified live: group-only, never fires in 1:1)',
    expectedEvent: 'message_read_by_all',
    automationMethod: 'SDK',
    expectedPayloadKeys: ['data.body.action', 'data.body.messageId', 'data.sender'],
    status: 'AUTOMATED',
    specFile: 'src/tests/message/message-read-by-all.spec.ts',
    testTitleMatch: 'message_read_by_all webhook fires once every group member has read the message',
  },
];
